import { Tile } from './classes/Tile'

let id = 0;
export const tiles: Tile[] = [
    new Tile(++id, false, true, false, true, 0),
    new Tile(++id, false, true, false, true, 0),
    new Tile(++id, false, true, true, false, 1),
    new Tile(++id, false, false, true, true, 1),
    new Tile(++id, false, true, true, true, 0),
    new Tile(++id, false, true, true, true, 0),
    new Tile(++id, true, true, true, true, 0),
    new Tile(++id, true, true, true, true, 0),
    new Tile(++id, true, true, false, false, 1),
    new Tile(++id, true, false, false, true, 1),
    new Tile(++id, true, true, false, true, 1),
    new Tile(++id, true, true, false, true, 0),
    new Tile(++id, false, true, false, true, 1),
    new Tile(++id, false, true, false, true, 2),
    new Tile(++id, false, true, false, true, 1),
    new Tile(++id, false, true, false, true, 2),
    new Tile(++id, true, false, true, false, 0),
    new Tile(++id, true, false, true, false, 0),
    new Tile(++id, false, true, false, true, 0),
    new Tile(++id, false, true, false, true, 0),
    new Tile(++id, false, true, true, false, 0),
    new Tile(++id, false, false, true, true, 0),
    new Tile(++id, true, true, true, false, 0),
    new Tile(++id, true, false, true, true, 0),
    new Tile(++id, true, true, true, true, 0),
    new Tile(++id, true, true, true, true, 0),
    new Tile(++id, true, true, false, false, 0),
    new Tile(++id, true, false, false, true, 0),
    new Tile(++id, true, true, true, false, 0),
    new Tile(++id, true, false, true, true, 0),
    new Tile(++id, true, false, true, false, 1),
    new Tile(++id, true, false, true, false, 2),
    new Tile(++id, true, false, true, false, 1),
    new Tile(++id, true, false, true, false, 2),
    new Tile(++id, true, false, true, false, 0),
    new Tile(++id, true, false, true, false, 0),
]